export const EventTypesColors = {
  Bootcamp: "navy",
  "Charitable auctions": "green",
  Charity: "blue",
  Corporate: "cyan",
  Exhibitions: "red",
  Family: "black",
  Fundraising: "yellow",
  Holiday: "orange",
  "Music events": "brown",
  "Networking events": "pink",
  "Product launches": "crimson",
  "Sponsored runs": "purple",
  "Sports events": "grey",
  "Trade shows": "darkblue",
};
